trigger: none

# this is being defined in app-ci pipeline
resources:
  pipelines:
  - pipeline: cd-pp
    source: ci-pipeline
    trigger: true

pool:
  vmImage: 'ubuntu-18.04' #ubuntu-latest

steps:
- script: 'pwd'
  displayName: 'Working path'

- script: 'ls --all'
  displayName: 'Path content'

- script: 'find .'
  displayName: 'Path all content visual'

- script: 'echo "$(Build.DefinitionName) | $(Build.BuildId) | $(Build.BuildNumber)" > buildinfo.txt'
  displayName: 'Write build info'
